apiVersion: v2
name: suite
description: A batteries-included Helm chart for Tinkerbell on a single node cluster using that host's network and NodePort services
type: application
version: 0.0.1

dependencies:
  - name: tinkerbell
    version: "0.0.1"
    repository: "file://../tinkerbell"
    condition: tinkerbell.enabled
  - name: showcase
    version: "0.0.3"
    repository: "file://../showcase"
    condition: showcase.enabled