apiVersion: v2
name: suite
description: A batteries-included Helm chart for Tinkerbell on a single node cluster using that host's network and NodePort services
type: application
version: 0.0.1

dependencies:
  - name: tinkerbell
    version: "^0" # See https://helm.sh/docs/chart_template_guide/function_list/#hyphen-range-comparisons et al
    repository: "file://../tinkerbell"
    condition: tinkerbell.enabled
  - name: showcase
    version: "^0" # See https://helm.sh/docs/chart_template_guide/function_list/#hyphen-range-comparisons et al
    repository: "file://../showcase"
    condition: showcase.enabled